### PR TITLE
resized logo in readme

### PR DESCRIPTION
**Pull request by jh2k2**
Hey, I am pretty new to contribution so any tip will be appreciated!

### CODE REVIEW

**Comment by CohenArthur** [comment]
Thanks a lot! The check failing is my bad, I'll fix it (or you can fix it yourself if you have rust installed, by executing `cargo fmt`).

What kind of tips would you like to get? 

Finally, this is a good contribution :) Is there any way you could make it so that the logo is flush with the text? Something like the following
```
jinko is a small and safe interpreted language written in     LOGO LOGO
Rust, with integrated unit tests, mocking and FFI.            LOGO LOGO
```
If you see what I mean?

**Comment by jh2k2** [comment]
> Thanks a lot! The check failing is my bad, I'll fix it (or you can fix it yourself if you have rust installed, by executing `cargo fmt`) (and if not I'll just merge it and fix it later. This is not a Code-related PR)
> 
> What kind of tips would you like to get?
> 
> Finally, this is a good contribution :) Is there any way you could make it so that the logo is flush with the text? Something like the following
> 
> ```
> jinko is a small and safe interpreted language written in     LOGO LOGO
> Rust, with integrated unit tests, mocking and FFI.            LOGO LOGO
> ```
> 
> If you see what I mean?

Any tips would be fine, and I will make attempt on the logo to flush with the text!

**Comment by jh2k2** [comment]
Hey is there any way to see the preview of the readme? I am rather inexperienced when it comes to GitHub actions.

**Comment by CohenArthur** [comment]
Do not worry about closing it, it's fine if you keep working on it while the PR is open. You can see the preview in your branch, by clicking the preview button on the file or just opening it

**Comment by jh2k2** [comment]
Ah! Thanks for the headsup

**Comment by CohenArthur** [comment]
I'd put it slightly bigger, like 8 or 10% and it's perfect! Thanks a lot!

**Comment by jh2k2** [comment]
No problem at all! Thanks for the learning opportunity

**Review by CohenArthur — APPROVED** [review]
Perfect! Thanks a lot :) If you're interested in developing the language feel free to take a crack at the other issues!

**Comment by jh2k2** [comment]
Thanks I'm glad to contribute to this project as my first merge

**Pull request merged**
